# Generated by Django 4.0.3 on 2022-04-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('number', models.CharField(default='1.1.1', max_length=10, primary_key=True, serialize=False)),
                ('table_num', models.PositiveSmallIntegerField(default=1)),
                ('sub_num', models.PositiveSmallIntegerField(default=1)),
                ('book_num', models.PositiveSmallIntegerField(default=1)),
                ('book_name', models.CharField(default='', max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('edition', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='issuebook',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=12)),
                ('enrollment', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('book', models.CharField(max_length=10)),
            ],
        ),
    ]
