# Generated by Django 4.0.3 on 2022-04-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_issuebook_cur_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='cur_date',
            new_name='issue_date',
        ),
    ]
