# Generated by Django 4.0.3 on 2022-04-23 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0004_alter_issuebook_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='isreturn',
            field=models.CharField(default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='book',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='enrollment',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(default=datetime.date(2022, 4, 23), null=True),
        ),
    ]
