# Generated by Django 4.0.3 on 2022-04-24 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0005_issuebook_isreturn_alter_issuebook_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='ret_date',
            field=models.DateField(default=datetime.date(2022, 4, 24)),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(default=datetime.date(2022, 4, 24)),
        ),
    ]
