# Generated by Django 4.0.3 on 2022-04-26 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0006_issuebook_ret_date_alter_issuebook_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='test',
            field=models.PositiveIntegerField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(default=datetime.date(2022, 4, 26)),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='ret_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
