# Generated by Django 4.0.3 on 2022-04-27 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0007_issuebook_test_alter_issuebook_issue_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='ret_date',
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='test',
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
    ]
